In [16]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [4]:
# class type exmaple
class TestClass():
  def __init__(self):
    self.a = 1
    self.b = 2

  def sum(self):
    return self.a + self.b


In [5]:
testclass = TestClass()

testclass.sum()

3

In [7]:
# label encoder
items = ['TV', 'fridge', 'mcwave', 'computer', 'fan', 'fan','mixer', 'fridge']

le_enc = LabelEncoder()

le_enc.fit(items)

le_enc.transform(items)
# TV > 0, fridge > 1, mcwave > 4, computer > 5, fan > 3, mixer > 2
le_enc.transform(items)

array([0, 3, 4, 1, 2, 2, 5, 3])

In [8]:
import seaborn as sns

iris = sns.load_dataset('iris')

le_enc = LabelEncoder() # 새로운 데이터에 대해서 학습할때는 다시 호출

le_enc.fit(iris['species'])

LabelEncoder()

In [9]:
iris['species'] = le_enc.transform(iris['species'])

In [10]:
iris

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [11]:
le_enc = LabelEncoder()

# le_enc.fit(items)
# items2 = le_enc.transform(items)

items2 = le_enc.fit_transform(items)
print(items2)

[0 3 4 1 2 2 5 3]


In [12]:
le_enc.classes_

array(['TV', 'computer', 'fan', 'fridge', 'mcwave', 'mixer'], dtype='<U8')

In [13]:
le_enc.inverse_transform([0, 1, 5])

array(['TV', 'computer', 'mixer'], dtype='<U8')

In [14]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
items = ['TV', 'fridge', 'mcwave', 'computer', 'fan', 'fan',
'mixer', 'fridge']
items = np.array(items).reshape(-1, 1)
items

array([['TV'],
       ['fridge'],
       ['mcwave'],
       ['computer'],
       ['fan'],
       ['fan'],
       ['mixer'],
       ['fridge']], dtype='<U8')

In [17]:
oh_enc = OneHotEncoder()
oh_enc.fit(items)
result = oh_enc.transform(items)
pd.DataFrame(result.toarray())

0    1    2    3    4    5
0  1.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  1.0  0.0  0.0
2  0.0  0.0  0.0  0.0  1.0  0.0
3  0.0  1.0  0.0  0.0  0.0  0.0
4  0.0  0.0  1.0  0.0  0.0  0.0
5  0.0  0.0  1.0  0.0  0.0  0.0
6  0.0  0.0  0.0  0.0  0.0  1.0
7  0.0  0.0  0.0  1.0  0.0  0.0

In [18]:
import pandas as pd

df = pd.DataFrame({'item':['TV', 'fridge', 'mcwave', 'computer',
                  'fan', 'fan', 'mixer', 'fridge']})
df

s = pd.Series(['TV', 'fridge', 'mcwave', 'computer',
                  'fan', 'fan', 'mixer', 'fridge'])
s

0          TV
1      fridge
2      mcwave
3    computer
4         fan
5         fan
6       mixer
7      fridge
dtype: object

In [19]:
pd.get_dummies(s)

TV  computer    fan  fridge  mcwave  mixer
0   True     False  False   False   False  False
1  False     False  False    True   False  False
2  False     False  False   False    True  False
3  False      True  False   False   False  False
4  False     False   True   False   False  False
5  False     False   True   False   False  False
6  False     False  False   False   False   True
7  False     False  False    True   False  False

In [20]:
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [21]:
oh_enc = OneHotEncoder()

oh_enc.fit(iris[['species']])

OneHotEncoder()

In [22]:
result = oh_enc.transform(iris[['species']])

In [23]:
print(result)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 150 stored elements and shape (150, 3)>
  Coords	Values
  (0, 0)	1.0
  (1, 0)	1.0
  (2, 0)	1.0
  (3, 0)	1.0
  (4, 0)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 0)	1.0
  (12, 0)	1.0
  (13, 0)	1.0
  (14, 0)	1.0
  (15, 0)	1.0
  (16, 0)	1.0
  (17, 0)	1.0
  (18, 0)	1.0
  (19, 0)	1.0
  (20, 0)	1.0
  (21, 0)	1.0
  (22, 0)	1.0
  (23, 0)	1.0
  (24, 0)	1.0
  :	:
  (125, 2)	1.0
  (126, 2)	1.0
  (127, 2)	1.0
  (128, 2)	1.0
  (129, 2)	1.0
  (130, 2)	1.0
  (131, 2)	1.0
  (132, 2)	1.0
  (133, 2)	1.0
  (134, 2)	1.0
  (135, 2)	1.0
  (136, 2)	1.0
  (137, 2)	1.0
  (138, 2)	1.0
  (139, 2)	1.0
  (140, 2)	1.0
  (141, 2)	1.0
  (142, 2)	1.0
  (143, 2)	1.0
  (144, 2)	1.0
  (145, 2)	1.0
  (146, 2)	1.0
  (147, 2)	1.0
  (148, 2)	1.0
  (149, 2)	1.0


In [24]:
iris_enc = pd.DataFrame(result.toarray(), columns = oh_enc.categories_)
iris_enc.head()

setosa versicolor virginica
0    1.0        0.0       0.0
1    1.0        0.0       0.0
2    1.0        0.0       0.0
3    1.0        0.0       0.0
4    1.0        0.0       0.0

In [25]:
oh_enc.categories_

[array(['setosa', 'versicolor', 'virginica'], dtype=object)]

In [26]:
pd.concat([iris.drop('species', axis = 1), iris_enc], axis = 1)

sepal_length  sepal_width  petal_length  petal_width  (setosa,)  \
0             5.1          3.5           1.4          0.2        1.0   
1             4.9          3.0           1.4          0.2        1.0   
2             4.7          3.2           1.3          0.2        1.0   
3             4.6          3.1           1.5          0.2        1.0   
4             5.0          3.6           1.4          0.2        1.0   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3        0.0   
146           6.3          2.5           5.0          1.9        0.0   
147           6.5          3.0           5.2          2.0        0.0   
148           6.2          3.4           5.4          2.3        0.0   
149           5.9          3.0           5.1          1.8        0.0   

     (versicolor,)  (virginica,)  
0              0.0           0.0  
1              0.0           0.0  
2              0.0           0.0  
3              0.0           0.0  
4              0.0           0.0  
..             ...           ...  
145            0.0           1.0  
146            0.0           1.0  
147            0.0           1.0  
148            0.0           1.0  
149            0.0           1.0  

[150 rows x 7 columns]

In [27]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [28]:
pd.get_dummies(iris['species'])

setosa  versicolor  virginica
0      True       False      False
1      True       False      False
2      True       False      False
3      True       False      False
4      True       False      False
..      ...         ...        ...
145   False       False       True
146   False       False       True
147   False       False       True
148   False       False       True
149   False       False       True

[150 rows x 3 columns]

In [29]:
pd.concat([iris.drop('species', axis = 1), pd.get_dummies(iris['species'])], axis = 1)

sepal_length  sepal_width  petal_length  petal_width  setosa  versicolor  \
0             5.1          3.5           1.4          0.2    True       False   
1             4.9          3.0           1.4          0.2    True       False   
2             4.7          3.2           1.3          0.2    True       False   
3             4.6          3.1           1.5          0.2    True       False   
4             5.0          3.6           1.4          0.2    True       False   
..            ...          ...           ...          ...     ...         ...   
145           6.7          3.0           5.2          2.3   False       False   
146           6.3          2.5           5.0          1.9   False       False   
147           6.5          3.0           5.2          2.0   False       False   
148           6.2          3.4           5.4          2.3   False       False   
149           5.9          3.0           5.1          1.8   False       False   

     virginica  
0        False  
1        False  
2        False  
3        False  
4        False  
..         ...  
145       True  
146       True  
147       True  
148       True  
149       True  

[150 rows x 7 columns]

In [30]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)
print('features average :\n', iris_df.mean())
print('features variation :\n', iris_df.var())


features average :
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
features variation :
 sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [31]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [32]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

sc.fit(iris_df)

StandardScaler()

In [33]:
iris_scaled = sc.transform(iris_df)
iris_df_scaled = pd.DataFrame(data = iris_scaled,
columns = iris.feature_names)


In [34]:
iris_df_scaled.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444

In [35]:
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [36]:
iris_df_scaled.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count       1.500000e+02      1.500000e+02       1.500000e+02   
mean       -1.468455e-15     -1.823726e-15      -1.610564e-15   
std         1.003350e+00      1.003350e+00       1.003350e+00   
min        -1.870024e+00     -2.433947e+00      -1.567576e+00   
25%        -9.006812e-01     -5.923730e-01      -1.226552e+00   
50%        -5.250608e-02     -1.319795e-01       3.364776e-01   
75%         6.745011e-01      5.586108e-01       7.627583e-01   
max         2.492019e+00      3.090775e+00       1.785832e+00   

       petal width (cm)  
count      1.500000e+02  
mean      -9.473903e-16  
std        1.003350e+00  
min       -1.447076e+00  
25%       -1.183812e+00  
50%        1.325097e-01  
75%        7.906707e-01  
max        1.712096e+00

In [37]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data = iris_scaled,
columns = iris.feature_names)
iris_df_scaled.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.222222          0.625000           0.067797          0.041667
1           0.166667          0.416667           0.067797          0.041667
2           0.111111          0.500000           0.050847          0.041667
3           0.083333          0.458333           0.084746          0.041667
4           0.194444          0.666667           0.067797          0.041667

In [38]:
iris_df_scaled.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            0.428704          0.440556           0.467458   
std             0.230018          0.181611           0.299203   
min             0.000000          0.000000           0.000000   
25%             0.222222          0.333333           0.101695   
50%             0.416667          0.416667           0.567797   
75%             0.583333          0.541667           0.694915   
max             1.000000          1.000000           1.000000   

       petal width (cm)  
count        150.000000  
mean           0.458056  
std            0.317599  
min            0.000000  
25%            0.083333  
50%            0.500000  
75%            0.708333  
max            1.000000

In [49]:
titanic_df = pd.read_csv('/Users/yongyong7777/Documents/ML_practice/data/titanic.csv')

In [50]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [51]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [52]:
titanic_df['Age'].mean()

np.float64(29.69911764705882)

In [53]:
# titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Age'].fillna(titanic_df['Age'].mean(), inplace=True)
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


/var/folders/8q/3bk4mhcd2l38k0_tbmtbbsv80000gn/T/ipykernel_11670/1498865016.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic_df['Age'].fillna(titanic_df['Age'].mean(), inplace=True)


In [54]:
titanic_df.drop('Cabin', axis=1, inplace=True)
titanic_df['Embarked'].fillna('N', inplace=True)

/var/folders/8q/3bk4mhcd2l38k0_tbmtbbsv80000gn/T/ipykernel_11670/3000155973.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic_df['Embarked'].fillna('N', inplace=True)


In [55]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object 
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB


In [57]:
print('Distribution of sex :\n', titanic_df['Sex'].value_counts())
print('Distribution of class :\n', titanic_df['Embarked'].value_counts())

Distribution of sex :
 Sex
male      577
female    314
Name: count, dtype: int64
Distribution of class :
 Embarked
S    644
C    168
Q     77
N      2
Name: count, dtype: int64


In [58]:
# Sex : LabelEncoder, Embarked : OneHotEncoder 쓰겠다.

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

lb_enc = LabelEncoder()
oh_enc = OneHotEncoder()

sex_enc = lb_enc.fit_transform(titanic_df['Sex'])
emb_enc = oh_enc.fit_transform(titanic_df[['Embarked']])

In [59]:
emb_enc

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 891 stored elements and shape (891, 4)>

In [60]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [61]:
titanic_df.drop(['PassengerId', 'Name', 'Ticket', 'Sex', 'Embarked'], axis=1, inplace=True)

In [62]:
titanic_df['Sex'] = sex_enc

In [63]:
titanic_df.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Sex
0         0       3  22.0      1      0   7.2500    1
1         1       1  38.0      1      0  71.2833    0
2         1       3  26.0      0      0   7.9250    0
3         1       1  35.0      1      0  53.1000    0
4         0       3  35.0      0      0   8.0500    1

In [64]:
emb_df = pd.DataFrame(emb_enc.toarray())

In [65]:
titanic = pd.concat([titanic_df, emb_df], axis = 1)

In [66]:
titanic.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Sex    0    1    2    3
0         0       3  22.0      1      0   7.2500    1  0.0  0.0  0.0  1.0
1         1       1  38.0      1      0  71.2833    0  1.0  0.0  0.0  0.0
2         1       3  26.0      0      0   7.9250    0  0.0  0.0  0.0  1.0
3         1       1  35.0      1      0  53.1000    0  0.0  0.0  0.0  1.0
4         0       3  35.0      0      0   8.0500    1  0.0  0.0  0.0  1.0

In [67]:
X = titanic.iloc[:, 1:]
Y = titanic.iloc[:, 0]

In [68]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

s_scaler = StandardScaler()
m_scaler = MinMaxScaler()

X_s = s_scaler.fit_transform(X.values)
X_m = m_scaler.fit_transform(X.values)

In [69]:
X_s

array([[ 0.82737724, -0.5924806 ,  0.43279337, ..., -0.0474312 ,
        -0.30756234,  0.61930636],
       [-1.56610693,  0.63878901,  0.43279337, ..., -0.0474312 ,
        -0.30756234, -1.61470971],
       [ 0.82737724, -0.2846632 , -0.4745452 , ..., -0.0474312 ,
        -0.30756234,  0.61930636],
       ...,
       [ 0.82737724,  0.        ,  0.43279337, ..., -0.0474312 ,
        -0.30756234,  0.61930636],
       [-1.56610693, -0.2846632 , -0.4745452 , ..., -0.0474312 ,
        -0.30756234, -1.61470971],
       [ 0.82737724,  0.17706291, -0.4745452 , ..., -0.0474312 ,
         3.25137334, -1.61470971]], shape=(891, 10))

In [70]:
X_m

array([[1.        , 0.27117366, 0.125     , ..., 0.        , 0.        ,
        1.        ],
       [0.        , 0.4722292 , 0.125     , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.32143755, 0.        , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [1.        , 0.36792055, 0.125     , ..., 0.        , 0.        ,
        1.        ],
       [0.        , 0.32143755, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.39683338, 0.        , ..., 0.        , 1.        ,
        0.        ]], shape=(891, 10))

In [71]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier()

dt_clf1 = DecisionTreeClassifier(random_state = 0)
dt_clf2 = DecisionTreeClassifier(random_state = 0)
dt_clf3 = DecisionTreeClassifier(random_state = 0)

dt_clf1.fit(X_s, Y)
dt_clf2.fit(X_m, Y)
dt_clf3.fit(X.values, Y)

DecisionTreeClassifier(random_state=0)

In [72]:
from sklearn.model_selection import cross_val_score

score1 = cross_val_score(rf_clf, X_s, Y, scoring='accuracy', cv=5)
score2 = cross_val_score(rf_clf, X_m, Y, scoring='accuracy', cv=5)
score3 = cross_val_score(rf_clf, X.values, Y, scoring='accuracy', cv=5)

In [73]:
print(score1.mean())
print(score2.mean())
print(score3.mean())

0.8148515472977215
0.8081099742640137
0.8103634423451134


In [76]:
titanic_df = pd.read_csv('/Users/yongyong7777/Documents/ML_practice/data/titanic.csv')
titanic_df['Cabin'].value_counts(dropna=False)

Cabin
NaN            687
C23 C25 C27      4
G6               4
B96 B98          4
C22 C26          3
              ... 
E34              1
C7               1
C54              1
E36              1
C148             1
Name: count, Length: 148, dtype: int64

In [77]:
titanic_df['Cabin'].fillna('N', inplace=True)

/var/folders/8q/3bk4mhcd2l38k0_tbmtbbsv80000gn/T/ipykernel_11670/3429797980.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic_df['Cabin'].fillna('N', inplace=True)


In [78]:
titanic_cabin = titanic_df['Cabin'].apply(lambda x: x[0])

In [79]:
titanic_cabin.value_counts()

Cabin
N    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [80]:
def get_category(age):
  cat = ''
  if age <= -1:
    cat = 'Unknown'
  elif age <= 5:
    cat = 'Baby'
  elif age <= 12:
    cat = 'Child'
  elif age <= 18:
    cat = 'Teenager'
  elif age <= 25:
    cat = 'Student'
  elif age <= 35:
    cat = 'Young Adult'
  elif age <= 60:
    cat = 'Adult'
  else :
    cat = 'Elderly'
  return cat


In [81]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=0)

In [82]:
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier()

dt_clf.fit(X_train.values, Y_train)

pred = dt_clf.predict(X_test.values)

In [83]:
pred

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1])

In [84]:
from sklearn.metrics import accuracy_score

print('정확도 :', accuracy_score(Y_test, pred))

정확도 : 0.7877094972067039


In [85]:
from sklearn.metrics import confusion_matrix

print('Error Matrix\n', confusion_matrix(Y_test, pred))

Error Matrix
 [[94 16]
 [22 47]]


In [86]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

print('Precision :', precision_score(Y_test, pred))
print('Recall :', recall_score(Y_test, pred))

Precision : 0.746031746031746
Recall : 0.6811594202898551


In [87]:
from sklearn.metrics import f1_score

print('F1_Score :', f1_score(Y_test, pred))

F1_Score : 0.7121212121212122


In [88]:
# roc_auc_score
from sklearn.metrics import roc_auc_score

print('ROC_AUC :',roc_auc_score(Y_test, pred))

ROC_AUC : 0.7678524374176547


In [89]:

pred = dt_clf.predict(X_test.values)
pred

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1])

In [90]:
pred_proba = dt_clf.predict_proba(X_test.values)[:, 1]
pred_proba

array([0.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 1.        , 1.        , 1.        , 1.        ,
       0.        , 1.        , 0.11111111, 1.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.33333333, 1.        , 1.        , 0.        ,
       0.        , 1.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 1.        , 0.        , 0.        ,
       0.        , 0.        , 1.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 1.        , 1.        , 0.        , 1.        ,
       0.        , 1.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 1.        , 0.        , 0.     

In [91]:
for i, v in enumerate(pred_proba):
  if v >= 0.3:
    pred_proba[i] = 1
  else:
    pred_proba[i] = 0
pred_proba


array([0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 0., 1.])

In [92]:
pred

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1])

In [93]:
# roc_auc

roc_auc_score(Y_test, pred_proba)

0.7705533596837945